### ISSUE TITLE
Lag when switching Widgets if the timeframe is allocated across two days

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/viewer#101]
**How to recreate**
Allocate two Widgets which changes across two days.  See https://apps.risevision.com/editor/workspace/abaedcc0-b27e-4b98-9b24-0862097daad4/?cid=960b72df-9af7-476b-8a47-b67ded4c779d

On a local machine, change local time to be 11:57pm July 30.

**What is observed**

July 30 11:58:00pm You see the correct Placeholder content “SAT July 30 2am - 11:59pm”

July 30 11:59:30pm it states that “Nothing has been scheduled”

July 31 12:00:00am it still states that nothing is scheduled

July 31 12:00:35am it switches to “SUN July 31 12:00am -2am” which is the correct Placeholder

**What should happen**
No gap in between switching content when the Viewer goes to another day

**Comment by hcs0** [comment]
https://app.intercom.io/a/apps/d85f4ah4/inbox/hcs@risevision.com/conversations/5418380770

**Comment by robb-price** [comment]
Fixed with the new version.

**Comment by alex-deaconu** [comment]
PR #211 which fixes this issue is now deployed. Closing.
