### ISSUE TITLE
Republishing a presentation can lead to a viewer crash

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/viewer#103]
**How to Recreate**

Use this <a href="https://apps.risevision.com/editor/workspace/fb916fdf-0a4e-4abe-89d6-cee76f64c605/?cid=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55">presentation</a> containing 4 Image Widgets.

One image widget links to an 81MB image file.

Allocate to a Display running Win 10x32 (also observed on Win 7x2).  

Run the presentation.

Resave and Republish the Presentation.

**What happens**
After resaving and republishing the Presentation it can lead to a crash straight away.

5 out of 7 tests on Uptime Win 10 x32 897M crashes within 0-3min
2 out of 7 tests on Uptime V3 Win 7 x32 REGG crashes within 0-3min
In other tests it takes longer to crash (ie 8min, 11min, 26min...) or no crash (after observing 60min)

After publishing, seeing a spike in CPU Usage for both OS.

**Notes**
Observed on Win 7 x32 and Win 10x32 on the Uptime Wall 
Crashes were also observed on two test machines (one Win 7 NUC and one Win 10x32 Intel Compute Stick)
Crash not observed on another test machine (Win 7x 32) running the presentation for 60min.
Occurred when it was on Chr 51 and still occurs in Chr 52.

During Chr 51 testing in early <a href="https://plus.google.com/107081894828094649852/posts/A6ZrRJ6c93j">June</a>, we found a similar issue where after a schedule or presentation change it led to a viewer crash.

**Comment by ByronDarlison** [comment]
Thanks @hcs0 . @alex-deaconu is this a viewer issue or could it be related to chromium 52, or possibly an image widget issue? @tejohnso @alanclayton @rodrigopavezi @ezequielc thoughts?

Thanks

**Comment by alex-deaconu** [comment]
This is related to Publishing a Presentation containing Large Image files being used in the Image Widget on 32-bit machines. Most likely a Chrome issue, but could potentially be a Widget issue, least likely (according to our investigation) a Viewer issue. Closing this on the Viewer side, up to Delivery if they want to pursue investigating and fixing in the Widget.

Thanks!
