### ISSUE TITLE
Video's don't fallback to being stored in Browser cache if Rise Cache is unavailable

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/viewer#11]
If for whatever reason Rise Cache is unavailable, Viewer will download a video each time it is played in a Presentation resulting in excessive bandwidth. If Rise Cache is unavailable, we should use browser cache to prevent excessive bandwidth usage.

**Comment by ByronDarlison** [comment]
@alanclayton can you confirm if this is now closed? Thanks

**Comment by alanclayton** [comment]
@ByronDarlison Yes, I think we can close this.
