### ISSUE TITLE
Video's within an embedded Presentation are not stored in Rise Cache

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/viewer#13]
Embed a Presentation that includes a video and run on a Display. From Chrome Dev Tools, look at the Network tab where you can verify it is downloaded from the hosting server every time it plays vs being served from Rise Cache.

**Comment by mfisher11** [comment]
This still appears to be an issue.  I have tested it with the current and testing versions of player (1.24.28 and 1.24.30) with the default/current viewer and the one specified above (1-06-030.rvashow2.appspot.com).

Steps to reproduce:

1. Run a presentation containing another presentation with a video.
2. Clear the rise cache (with the "clear cache" button from the config screen)
3. Verify the cache is cleared (with the "show cached files" button)
4. Exit the player.
5. Relaunch player, immediately right click and select inspect element,  then switch to the network tab
6. In the presentation linked below, I see two requests referencing the video:
https://storage.googleapis.com/risemedialibrary-xxxxxxx/video_file (GET) video/mp4          and
https://storage.googleapis.com/risemedialibrary-xxxxxxx/video_file (HEAD)
7. Click on "show cached files" and verify that the appropriately-sized file for the video is present.
<repeat steps 4 and 5>

Expected results:   the entry in the network tab pertaining to the video should be a rise cache url:
http://localhost:9494/ping?callback=jQuery...   or
http://localhost:9494/<storage url>

Actual results:
https://storage.googleapis.com/risemedialibrary-xxxxxxx/video_file (HEAD)

Link to presentation:
http://rvauser.appspot.com/#/PRESENTATION_MANAGE/id=f7c827f7-e536-4d29-b8b8-7ba67ec5a8e9?cid=e514fd51-fadd-4e19-94af-f92549772c7f

OS:
Linux, Windows, OSX, (presumably chrome os)

**Comment by ByronDarlison** [comment]
embedded presentations are deprecated, won't fix
