### ISSUE TITLE
White Presentation shows on Display when no content is schedule in Presentation

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/viewer#130]
When two Presentations are in a Schedule (Presentation A & Presentation B), both configured in the Schedule to show 24/7, but the content of Presentation B scheduled to show at specific times of the day, on most OS's Viewer shows all white when content from Presentation B shouldn't be showing. 

On Ubuntu 14.04 x 64, Viewer will show a message saying there are no Presentations or Web Pages Schedule. http://www.screencast.com/t/FVucHMHc3y9

What Should Happen:
If content is not scheduled to show in the Presentation, Viewer shouldn't try showing it and move to the next Presentation it the respective Schedule. 

You can replicate this by assigning your Display to this Schedule, https://goo.gl/tdUJ0j

Player version: RisePlayerElectron 2016-07-22-12-00
OS: Ubuntu 14.04, Win 7, Win 10

**Comment by robb-price** [comment]
Issue is corrected in new version.

**Comment by alex-deaconu** [comment]
PR #211 which fixes this issue is now deployed. Closing.
