### ISSUE TITLE
Displays not responding properly when removed from Schedule

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/viewer#133]
Viewer: 2-00-201609201528
Player: RisePlayerElectron 2016.09.29.23.54
Displays: JAQVBQS84SGK, MMZ4NHZA3RCG, (more if needed)

Win 7, Win 10, Lnx 14.04

1. Assign your Display to this Schedule https://goo.gl/4MCKnw
2. Wait for content to show on display
3. Remove the Display from the Schedule

The Displays continue to show the presentations in the schedule. 

The Displays should show the msg stating The Display ha sno Presentations or Web Pages Scheduled.

**Comment by tejohnso** [comment]
@alexey-rise It looks like the content-update message isn't coming through the messaging service when a display is removed from a schedule.   It's coming through correctly when a display is added to a schedule.  @alanclayton FYI

**Comment by alanclayton** [comment]
@alexey-rise see https://goo.gl/uxTyzS

**Comment by alexey-rise** [comment]
@alanclayton @tejohnso fixed and deployed, please verify.

**Comment by alanclayton** [comment]
@alexey-rise verified.
