### ISSUE TITLE
Video Item configured with youtube won't play on Display

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/viewer#136]
Viewer: 2-00-201609292007
Presentation: https://goo.gl/OM97MC

Video Item won't play youtube URL's when running on a Display (v1, v2 and v3) 

Youtube video plays as expected in Preview.

**Comment by ezequielc** [comment]
@alanclayton I verified that this is an existing issue, so it will be given less priority and will not block us from releasing a new viewer version. We are still working on https://github.com/Rise-Vision/viewer/issues/137 before releasing the version you tested on Friday. 
Could you confirm?  Thanks

@alex-deaconu fyi

**Comment by alanclayton** [comment]
@ezequielc if this is an existing issue then do we even need to worry about it given video item is discontinued. I was under the impression a common use case with video item was to show a youtube URL, but doesn't sound like that is the case.

**Comment by ezequielc** [comment]
@alanclayton Yes, you are right. There is no need to fix this. I will close this issue. Thanks!

**Comment by alanclayton** [comment]
@ezequielc I reviewed again and using the full URL works so indeed this is nothing we need to worry about. Thanks
