### ISSUE TITLE
Viewer randomly flashes white screen in between playlist items.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/viewer#141]
**How to recreate**
Assign multiple Image Widgets w/images to a placeholder in two presentations. (Test presentations [here](https://apps.risevision.com/editor/workspace/28e2500a-ed80-4ac7-8434-dd40131ff9f9/?cid=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55) and [here](https://apps.risevision.com/editor/workspace/f703276f-217b-404d-830d-f596767955c3/?cid=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55).)
Set the transition of those placeholders to "None".
Assign both presentations to a schedule.
Assign schedule to a display.

**What happens**
The presentation will play through the placeholder items, occasionally, the screen will flash white in between the placeholder items.

**What should happen**
1) The presentation should
 - Play image after image with no white flash

2) The schedule should
 - Play scheduled presentations no white flash

**Notes**
Video [here](http://www.screencast.com/t/NvlaMmBJ)
Schedule [here](https://apps.risevision.com/schedules/details/600c0db4-bfef-4ff7-847f-eaa2f6d74454?cid=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55)

**Comment by alex-deaconu** [comment]
@btfrise does this happen with any other Widget or content item? If it is specific to the Image Widget, I would venture to say it's a Widget issue. Thanks.

**Comment by btfrise** [comment]
@alex-deaconu I've tested with calendar/web page/video and cannot recreate.  I'll move this defect.

**Comment by alex-deaconu** [comment]
@btfrise thanks!
