### ISSUE TITLE
Display ID, Claim ID, Help and Quit buttons don't work on v3 and v1 Players

### ISSUE THREAD

**Issue by ezequielc** [Rise-Vision/viewer#142]
On the production viewer, if I assign a display ID to a v3 or v1 player then delete that display, Viewer shows the Display ID / Claim ID / Help / Quit prompt. None of the buttons work.

In v3 users have to reinstall if they want to change their display id. 
We could show a link to the player download page instead of the Display ID / Claim ID / Help / Quit prompt.

**Comment by robb-price** [comment]
@ezequielc This also occurs on the Cenique Player, however users can still add the Display ID/Claim ID in the Cenique Player settings, so it is not critical on the Cenique Player as well.

**Comment by alanclayton** [comment]
This is fixed on v3 player with version 8.8.2017. User choose if to change Display ID prior to content showing. If the display id is invalid, we will present the appropriate ui for user to update their id, or use claim id.
