### ISSUE TITLE
Interactions don't work in preview.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/viewer#148]
**How to replicate**
1. Add any interactive Widget to a placeholder (web page widget for example)
2. In presentation settings, uncheck "Hide mouse pointer"
3. Preview presentation

**What happens**
The presentation cannot be interacted with unless you append &showui=false to the end of the preview URL.

**What should happen**
The presentation should be interactive.

**Notes**
Example presentations:
[https://goo.gl/zmbfIa](https://goo.gl/zmbfIa) - web page widget
[https://goo.gl/e9RviO](https://goo.gl/e9RviO) - marketwall

Chrome Version 54.0.2840.59 (64-bit)

**Comment by ezequielc** [comment]
@btfrise Just to confirm, this issue is happening in QA or production version? Thanks
@alex-deaconu @fjvallarino @settinghead  fyi

**Comment by btfrise** [comment]
@ezequielc this is happening on production

**Comment by ezequielc** [comment]
@btfrise Ok, thanks!

**Comment by alex-deaconu** [comment]
@ezequielc @btfrise was able to replicate this as well. From what I can tell it occurs due to the `PreviewWidget` taking up 100% of the screen and preventing interaction (even when "hidden").

Workaround for this is to set the `showui=false` parameter.

@settinghead FYI. Thanks.

**Comment by btfrise** [comment]
@settinghead @ezequielc Validated! Looks good!
