### ISSUE TITLE
When an Embedded Presenation is set to PUD, when it is not set to show, it shows a blank space in that Placeholder instead of skipping that item

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/viewer#153]
<b>How it works now:</b>
1. At rva.risevision.com, set an embedded Presentation to be PUD, and set it to show from a specific time, to a specific time. 
2. Notice that when it is NOT set to show, it just shows a blank space in that Placeholder instead of skipping that item.

For further calrification: https://goo.gl/eIzyva

<b>How it should work:</b>
Since the embedded Presentation is not set to show, it should skip that item.

**Comment by btfrise** [comment]
This happens on all player versions, OSes and architectures.

**Comment by btfrise** [comment]
@stulees This is resolved. I'll go ahead and close.
