### ISSUE TITLE
Incorrect catch clause

### ISSUE THREAD

**Issue by tejohnso** [Rise-Vision/viewer#166]
[This catch clause](https://github.com/Rise-Vision/viewer/blob/master/src-js/Viewer/Data/ViewerDataProvider.js#L51) won't be reached on retrieval error because `getJSON` returns immediately with a jqXHR object

@settinghead @ezequielc @fjvallarino

**Comment by alex-deaconu** [comment]
@tejohnso would you consider this resolved at this point? Thanks.
