### ISSUE TITLE
Not setting active state on connection

### ISSUE THREAD

**Issue by tejohnso** [Rise-Vision/viewer#169]
@ezequielc @fjvallarino @settinghead This double nested condition passage results in ACTIVE_STATE not being set on new channel connections coming from a state of INACTIVE_STATE. I think we should be in ACTIVE_STATE on MESSAGE_CONNECT.

```js
 if (message && state !== INITIAL_STATE) {
    if (message === channelConnectionProvider.MESSAGE.CONNECT ||
      message === channelConnectionProvider.MESSAGE.PING
      /* || message === channelConnectionProvider.MESSAGE.AYT */) {
      if (message !== channelConnectionProvider.MESSAGE.CONNECT	||
        state !== INACTIVE_STATE) {
        state = ACTIVE_STATE;
      }
```

https://github.com/Rise-Vision/viewer/blob/master/src-js/Viewer/Channel/ChannelConnectionController.js#L73

**Comment by fjvallarino** [comment]
@tejohnso it makes sense... The code never actively checks for ACTIVE_STATE, although the fact of not switching to it when MESSAGE_CONNECT is received could cause a reconnection loop if no other messages are received.

**Comment by tejohnso** [comment]
@fjvallarino The check for ACTIVE_STATE happens [over here](https://github.com/Rise-Vision/viewer/blob/master/src-js/Viewer/Data/ViewerDataController.js#L82).

ViewerDataController ends up sending out another api call because INACTIVE_STATE is still set in the ChannelConnectionController.  So we end up getting both a new channel connection and a new data call if no ping is received after connection.

I think that if we fix that, and also increase [the timeout on the ping expectation](https://github.com/Rise-Vision/viewer/blob/master/src-js/Viewer/Channel/ChannelConnectionController.js#L84) we'll be in much better shape.  Instead of ping interval + 3 minutes we can set it to ping interval * 4 to wait an hour.  The ping interval comes from the data that core sends and it's currently at 15 mins.  But three minutes is not enough time for core to get pings out to all displays.

**Comment by tejohnso** [comment]
This is being addressed [here](https://github.com/Rise-Vision/viewer/pull/171)

**Comment by tejohnso** [comment]
@alex-deaconu Given our previous discussions on [the pr](https://github.com/Rise-Vision/viewer/pull/171) I think we want to leave things as is, where ACTIVE_STATE is not set on MESSAGE_CONNECT.  If so, we can close this.  FYI @fjvallarino @ezequielc

**Comment by alex-deaconu** [comment]
@tejohnso agreed 👍
