### ISSUE TITLE
Pause not being called when a Playlist contains a single Gadget that is set to PUD

### ISSUE THREAD

**Issue by donnapep** [Rise-Vision/viewer#17]
Add 2 Gadgets to a Placeholder and set them both to PUD. Remove one of the Gadgets and then preview the Presentation. Notice that after the Gadget has played through and reports 'Done', the Viewer immediately tells the Gadget to play again. The Viewer should be telling the Gadget to pause first and then to play, as is the case when the Gadget is not set to PUD.

**Comment by ByronDarlison** [comment]
@donnapep can you confirm if this issue is still open? Thanks

**Comment by donnapep** [comment]
@ByronDarlison Yes, it is. Thx.

**Comment by ByronDarlison** [comment]
@donnapep thanks

**Comment by ByronDarlison** [comment]
@donnapep does this issue only impact gadgets? Or does it also impact widgets? Thanks

**Comment by donnapep** [comment]
@ByronDarlison Looks like it's happening with Widgets as well. Thx.

**Comment by ByronDarlison** [comment]
@donnapep thanks. @robb-price @alanclayton does this issue cause any problems or can we delay it awhile? Thanks

**Comment by robb-price** [comment]
@ByronDarlison I am fine with delaying.

**Comment by donnapep** [comment]
@ByronDarlison I wish I'd written in the original bug report what problem it was causing. I'd be OK with closing this altogether and reopening if we find it's causing issues.

**Comment by ByronDarlison** [comment]
@donnapep thanks. Closing...
