### ISSUE TITLE
When you have the timeline of any content set to Weekly, it will not show on a Display.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/viewer#173]
<b>How it works now:</b>
1. Assign any Widget, Placeholder, Schedule, or Presentation in a Schedule to be on a WEEKLY duration. Set the item to show today.
2. Notice that when you preview, you can see the item.
3. Notice that when you play this on a Display, it is blank in the spot the content should be showing. If you have a Schedule set to be Weekly, it will be black on the Display.

Schedule: https://apps.risevision.com/schedules/details/8dd7034d-0445-4c22-90d8-65ca93324810?cid=556323b8-984c-4127-aa08-4d73d019bcb8

<b>How it should work:</b>
Regardless of the schedule, if content is set to show, it should show.

**Comment by alex-deaconu** [comment]
Fixed & validated.
