### ISSUE TITLE
White Screen when for multiple instances of same Presentation in Schedule

### ISSUE THREAD

**Issue by ezequielc** [Rise-Vision/viewer#189]
I could not narrow down the issue, but I am opening the issue for investigation.

When adding the same Presentation multiple times in a Schedule, set to weekly and each item using different weekdays, a white screen is showing in the display.

Sample Presentation: https://apps.risevision.com/schedules/details/0a5e3d78-5102-4c7f-9d2f-8b4541ad991d?cid=f114ad26-949d-44b4-87e9-8528afc76ce4
Sample Display: http://preview.risevision.com/?type=display&player=true&id=JUGACBYRY8Z9

**Comment by alex-deaconu** [comment]
@ezequielc this issue has been fixed by the above commit. I've validated the fix by setting my clock to Friday as suggested. 

Wondering if you could verify & update the User this issue is relevant to.

Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu Thanks! I validated and notified the user. Cheers!

**Comment by alex-deaconu** [comment]
@ezequielc thanks!
