### ISSUE TITLE
Error message shows when it shouldn't 

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/viewer#204]
**What is not working/What is currently happening:**
An error message saying A Presentation has not been assigned to the schedule. But a presentation is playing behind the error message

**What is expected to work/What is the client expecting:**
No error message shows if a Presentation is scheduled

**What has been tried so far:**
Nothing yet

**Schedule**
https://apps.risevision.com/schedules/details/da34db3d-6956-4d74-8a82-898ccfd73be9?cid=7fa5ee92-7deb-450b-a8d5-e5ed648c575f

**Display**
https://apps.risevision.com/displays/details/7G4X4RS9R48Q?cid=7fa5ee92-7deb-450b-a8d5-e5ed648c575f

**Presentation**
https://apps.risevision.com/editor/workspace/4f9c5b6d-c615-493b-b4c8-50408dfba652/?cid=7fa5ee92-7deb-450b-a8d5-e5ed648c575f

**Picture**

![img_20161213_124822](https://cloud.githubusercontent.com/assets/9273546/21153284/cfb832e6-c137-11e6-9e31-8e0ac9ef2fcb.jpg)

**Comment by fjvallarino** [comment]
@sheadarlison this can be checked on this Viewer url: http://hide-no-presentations-message-dot-rvaviewer-test.appspot.com/Viewer.html

**Comment by fjvallarino** [comment]
@sheadarlison this fix has been deployed to production

**Comment by ezequielc** [comment]
@sheadarlison I will close this. Please re-open it if you cannot confirm the fix. Thanks
