### ISSUE TITLE
Widgets play longer than the set duration in the Placeholder.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/viewer#206]
<b>How it works now</b>
1. Play <a href="https://apps.risevision.com/editor/workspace/1bb71033-05ee-444f-9a31-961e87bc908d/?cid=556323b8-984c-4127-aa08-4d73d019bcb8">this Presentation</a> on a Display, notice that the Widgets stop and move to the next content item when expected.
2. Preview that same Presentation, and notice that the Widgets go longer than the set duration.

Wendi and Darius have reported in the forum that this occurs for them on a Display, however using that Presentation example, I was not able to recreate.

The forum conversation has several more details provided by Wendi and Darius: https://community.risevision.com/rise_vision_inc/topics/widgets-playing-longer-than-duration

<b>How it should work</b>
The Widgets should adhere to the set duration.

**Comment by ByronDarlison** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Widgets go longer than the set duration](https://trello.com/c/0HGSsTZy/2895-widgets-go-longer-than-the-set-duration)

**Comment by robb-price** [comment]
Watched the preview of the Presentation for 6 minutes, and everything went as expected. Notified Wendi in the forum, this is now closed.
