### ISSUE TITLE
Mouse cursor appears over the top of Viewer in Ubuntu 14.04.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/viewer#208]
**How to recreate**
Assign any presentation to an Ubuntu 14.04 display. Make sure "Hide mouse pointer" is selected in the presentation.

**What happens**
The mouse pointer displays over the top of the presentation. In addition, if Screenconnect is installed, it's taskbar icon shows on top of the presentation as well.

**Notes**
Operating System: 32-bit & 64-bit Ubuntu 14.04.3 LTS
Player Version: RisePlayerElectron 2016.12.05.22.14
Viewer Version: 2-01-201612201546

See the defect in action at https://connect.risevision.com/Host#Access/*KC_Uptime//81fb8c24-4b30-1a08-4289-b3aaa199dbe1

**Comment by btfrise** [comment]
FYI, we have a workaround for users with this issue, maybe it's something that could be implemented in the player itself?

sudo apt-get install unclutter
sudo gedit /etc/default/unclutter

change the following line:
EXTRA_OPTS="-idle 1 -root"
to
EXTRA_OPTS="-idle 2 -root"

nohup unclutter -idle 2 &

**Comment by btfrise** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 208 - Mouse cursor appears over top of presentations on Ubuntu 14.04 media players.](https://trello.com/c/kRKOa6cR/2928-issue-208-mouse-cursor-appears-over-top-of-presentations-on-ubuntu-14-04-media-players)

**Comment by alex-deaconu** [comment]
@btfrise does this happen if Screenconnect is not installed and the taskbar icon doesn't show up on top of the Presentation?

If not, I would say it's related to that; ie. the cursor is for the taskbar screen as it is in focus over the Viewer/Browser itself. 

Thanks.

**Comment by btfrise** [comment]
@alex-deaconu I will test without SC installed.

**Comment by alex-deaconu** [comment]
@btfrise thanks!

**Comment by btfrise** [comment]
@alex-deaconu Doesn't appear to be related to SC. I've only been able to recreate when a pointing device is plugged in. I will close for now.
