### ISSUE TITLE
Scheduled presentations show white screens after expiring. 

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/viewer#21]
Example:

Schedule has three presentations
1) Consists of one 1920x1080 placeholder with four images set to display 5 seconds each to run from 8am-5pm.
2) Consists of one 1920x1080 placeholder with one image set to display for 5 seconds  and run 24/7.
3) Consists of one 1920x1080 placeholder with one image set to display for 4 seconds and run 24/7.

From 5:01pm - 7:59am, this schedule should display two images at 5 seconds each. Instead, it shows four blank white screens for 20 seconds (Presentation 1), followed by presentation 2 and 3.

We have replicated this issue in other schedules locally.

**Comment by ByronDarlison** [comment]
@btfrise can you confirm if this issue is still open? Thanks

**Comment by ashleighalmeida** [comment]
@btfrise @ByronDarlison Presentation works as expected. Did not encounter the white screen. No longer an issue.

**Comment by ByronDarlison** [comment]
Thanks @ashleighalmeida
