### ISSUE TITLE
Right mouse click is enabled when Hide mouse pointer is selected.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/viewer#28]
When mouse pointer is hidden (http://screencast.com/t/a7VW5JoWjp), right click is available in presentation.

**Comment by ByronDarlison** [comment]
@btfrise can you confirm if this is still a problem? Thanks

**Comment by ashleighalmeida** [comment]
@btfrise @ByronDarlison Ran a presentation with mouse pointer hidden, no right click was available. Not an ongoing issue.
