### ISSUE TITLE
Stop command is being called when a Widget is the only item in a Playlist

### ISSUE THREAD

**Issue by donnapep** [Rise-Vision/viewer#30]
**What steps will reproduce the problem?**
1. Put a Widget into a Placeholder by itself and set it to be PUD.
2. Preview the Presentation.
3. After the Widget calls `done`, the `stop` command is called.

**What is the expected output? What do you see instead?**
The `stop` command should not be called. Instead, the `pause` command is what should be called. The `stop` command is normally reserved for when a Presentation in a Schedule has finished showing.

The Widget would normally destroy itself when a `stop` command is sent. As a result of this issue, Widgets will not be able to destroy themselves, and instead the Display is going to chew up resources unnecessarily even when that Widget is in a Presentation that is no longer showing.

**Comment by alanclayton** [comment]
@alex-deaconu per @stulees this issue is going to be a block for the Video Folder Widget. I assume nothing was ever done with this. Can you confirm? If correct, I think we should get this queued up for the next item on your schedule.

@ByronDarlison FYI

**Comment by alex-deaconu** [comment]
@donnapep can you double check the Issue description. You're saying Instead the `done` command should be called? Should that say `pause`?

Also, I don't understand how this is affecting the Video Folder Widget. In terms of the Viewer, `stop` and `pause` have such a confusing behaviour pattern, Widgets should probably treat them as one and the same command.

@alanclayton if we want to fix this, we'd have to do a whole review of when `stop` and `pause` are called to ensure everything is consistent.

@ByronDarlison FYI.

Thanks.

**Comment by alanclayton** [comment]
@alex-deaconu okay.

@donnapep @stulees let us know on the respective questions for you above.

**Comment by donnapep** [comment]
@alex-deaconu You're right. I think I must have meant `pause`, which would quickly be followed by `play` since it's the only item in the playlist.

Here's the difference between `pause` and `stop` - `pause` tells a Widget to just stop playing the video or cycling the slideshow or whatever the case may be, but that it should still maintain its state so that it can pick up from where it left off later on.

`stop` essentially tells the Widget that it doesn't need to maintain its state and that it can go ahead and destroy itself so that the memory it's using can be reclaimed. You would likely want to do this when you have multiple Presentations in a Schedule and you switch to the next Presentation. I thought there was another use case for `stop` but I can't quite remember what it is.

Due to this Github issue, we're not able to implement a proper `stop` function. The best we can ever do is pause it, but never destroy it and hence never free up the memory its using.

Hope that makes sense.

Thx.

**Comment by alex-deaconu** [comment]
@donnapep thanks for the confirmation.

The original intention for `pause` vs `stop` can be best described by a Video's behaviour. `pause` pauses the video, and `play` continues. `stop` pauses the video and resets it to the first frame, and `play` starts it back up. 

By the logic above, if the Video is the only item in the playlist, on `done` we call `stop` to reset its position to the beginning, before calling `play`. If Viewer called `pause` the Video would just stay at the end of its playback next time `play` is called. (Obviously the above assumes a dumb video that doesn't reset on done).

Also re: unloading on `stop`, the expectation of the Viewer is that the Widget is always loaded and ready in memory. First thing that comes to mind when you tell me that a Widget un-loads itself on `stop`, is that it may flicker when loading again on `play`.

@alanclayton let me know your thoughts on the above. 

Thanks.

**Comment by donnapep** [comment]
@alex-deaconu OK, sounds like more discussion is definitely needed around this. Given where we're going with web components, I wonder if it's worth worrying about?

**Comment by stulees** [comment]
@alex-deaconu regarding the expectation of the Viewer assuming that the Widget is always loaded and ready in memory, this was my concern with Video Folder Widget. If the widget is never un-loaded, a lot of memory could be allocated to video for a presentation that isn't necessarily on screen. I would assume this would be taxing on the Display.

My current issue with Video Widget (memory problems) made me rehash this Viewer bug to see about addressing it as more of a prevention to further memory related problems that might come up with these Video Widgets.

**Comment by alex-deaconu** [comment]
@stulees I don't think the best way to fix a memory leak is to un-allocate memory. Probably better to fix it at the source. However, that's just my opinion. 

Also, I don't think we ever had memory leaks in the Video Item so: either the Video element is not inherently leaky and there's a code error or you should use a Video player that has fixes for any memory issues Video elements may have.

Thanks.

**Comment by stulees** [comment]
@alex-deaconu Agreed re: fixing memory leak and have addressed JS issues in the code. Hoping this fixes things, will be testing that shortly. 

Memory leaks aside, maybe the `stop` and `pause` does require more discussion as I'm still inclined to think that it is better optimization to be un-loading widget content when `stop` command is called. As Donna mentioned though, maybe it's not worth worrying about. Thanks

**Comment by ByronDarlison** [comment]
@stulees @alanclayton @donnapep @alex-deaconu is this issue still open? Thanks

**Comment by donnapep** [comment]
@ByronDarlison I think we can close this one.
