### ISSUE TITLE
Endless spinner on startup due to missing function

### ISSUE THREAD

**Issue by tejohnso** [Rise-Vision/viewer#311]
![missing-function](https://user-images.githubusercontent.com/1511535/42040937-d5e418f0-7abe-11e8-97a1-60ae04c91ac9.png)

Looks like it's coming from https://github.com/Rise-Vision/viewer/blob/master/src-js/Viewer/Renderer/ScheduleRenderer.js#L17

@robb-price fyi

**Comment by tejohnso** [comment]
@robb-price I think this is okay now after a cache clearing in the player. Please close once verified.

**Comment by alanclayton** [comment]
@tejohnso @rudibravo what can we do to make this a better user experience?

**Comment by rudibravo** [comment]
@tejohnso @alanclayton if I understand correctly, we removed the cache from newer releases of viewer. Once everyone is in the current viewer, this should be outdated right?

**Comment by tejohnso** [comment]
@alanclayton @rudibravo I have this on our standup doc for discussion tomorrow.

**Comment by tejohnso** [comment]
@robb-price I'm closing this - please reopen if necessary.
