### ISSUE TITLE
Unable to scroll in websites displayed via the URL option in Schedule playlists

### ISSUE THREAD

**Issue by kaden-rise** [Rise-Vision/viewer#317]
**Expected Behavior:** 
Users can run custom URLs, which are web pages and scroll vertically if the site allows/expects it.

**Actual Behavior:** 
Users run custom URLs, which are web pages but they cannot scroll vertically.

**Steps to Reproduce**
1. Add a scroll-able website to your Schedule playlist.
2. Preview the Schedule and you won't be able to scroll. Same behavior occurs directly on Displays.

**Comment by btfrise** [comment]
Outside supported use case.
