### ISSUE TITLE
Resolution is sometimes reported incorrectly for ChromeOS and Windows devices.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/viewer#339]
### What is the expected behavior?
When your Display is running at a set resolution in the OS, this should be the reported resolution in the Display Settings.

### What is the actual behavior?
Sometimes, and we can't determine why, the resolution for some Windows and ChromeOS devices is reporting a different resolution than what is currently running.

### What steps can be taken to replicate the problem?
Not really sure, but we have some specific Display ID's that this has been reported with that are available.

**Comment by andrecardoso** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) [Issue 339] Resolution is sometimes reported incorrectly for ChromeOS and Windows devices (Viewer)](https://trello.com/c/sbK3tv1S/400-3-issue-339-resolution-is-sometimes-reported-incorrectly-for-chromeos-and-windows-devices-viewer)
