### ISSUE TITLE
The help text on the "Display ID not found" not working.

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/viewer#41]
1. Install the Rise Vision Chrome App, https://chrome.google.com/webstore/detail/rise-vision-chrome-app-pl/mfpgpdablffhbfofnhlpgmokokbahooi
2. Once installed start the App.
3. Once opened, try to select on the URL, www.risevision.com/player-registration. 

The link does not open.

What should happen
1. When a User selects the URL, a page identical to how a page is opened when selecting the Help button should appear.
2. The URL in the sentence, "Visit http://help.risevision.com/#/user/player/register-player for more details" should be updated to http://help.risevision.com/#/user/player/register-player

In addition, the URL associated with the Help button is incorrect. It should be updated to use the same as above, http://help.risevision.com/#/user/player/register-player

**Comment by lapinnoir** [comment]
@alanclayton Can close since this was recently addressed https://github.com/Rise-Vision/viewer/issues/76
