### ISSUE TITLE
Viewer does not receive "done" call from embedded presentations, embedded presentations that are PUD endlessly loop.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/viewer#43]
This issue is logged using the HTML5 Video Widget as an example. I have also recreated with Google Spreadsheet Widget, and Image Folder Widget.

Steps to reproduce:
1. Create presentation with only HTML5 video widget. Save presentation.
2. Create another presentation with one large placeholder, add multiple embedded presentations. Add the presentation containing the HTML5 Video Widget.
3. Set HTML5 Video Widget presentation to Play Until Done.

Result:
The presentation playlist stops at the HTML5 Video Widget presentation and the video endlessly loops.

How it should work:
The placeholder should move on to the next item in the presentation playlist.

Link to Presentation:
http://preview.risevision.com/Viewer.html?type=presentation&id=fcbae24f-ec23-4622-9981-7a50c771726c

OS:
OS X 10.10.2 / ChromeOS / Linux Ubuntu 14.04 (Chrome App Player)

Chrome Ver:
41.0.2272.89

**Comment by AlexKolenoff** [comment]
@btfrise @alanclayton FYI this issue is impacting William O'Neal.  He reported it in the community with Video and Image Folder Widget and I just reproduced it with Image Folder Widget only.

**Comment by ByronDarlison** [comment]
@AlexKolenoff does this only happen if there is certain content in the playlist of any kind of content? Thanks

**Comment by AlexKolenoff** [comment]
@ByronDarlison I'm not sure, the test I did was with Image Folder widget, and it was also reproduced with the HTML5 Video widget. 

I can do a test with just plain Text widget to see if it still happens.

**Comment by ByronDarlison** [comment]
@AlexKolenoff I suspect that it is the widgets, but not sure, rather than viewer. Can you test without them and let us know what you find? Thanks

**Comment by AlexKolenoff** [comment]
@ByronDarlison Okay, it seems you may be right.  In order to eliminate the widgets, I did a test with using the Video Item.  It just switched to the second embedded presentation as it should.  I will leave it up to see if it continues to switch back and forth.

**Comment by ByronDarlison** [comment]
@alex-deaconu okay. Let me know what you find this morning.

@donnapep @stulees could you review this defect and let us know your thoughts?

FYI @alanclayton @alex-deaconu

**Comment by donnapep** [comment]
@ByronDarlison @AlexKolenoff If this is an issue with the Widgets perhaps not sending the `done` command, then having the Image Folder Widget in a playlist with other items with PUD set on it would not work either. It would never move to the next item. So if that scenario doesn't work, then it's a Widget issue; if it does work, then it's likely not a Widget issue. Thx.

**Comment by ByronDarlison** [comment]
@donnapep good point. @AlexKolenoff if you can test the possible combinations and let us know the conclusion it would be appreciated. Thanks

**Comment by alex-deaconu** [comment]
@ByronDarlison I'm pretty sure at this point this is a Viewer issue. Not sure if there's a need to investigate further in terms of QA. I'll address it in order of priority (if it becomes a priority). Thanks!

**Comment by ByronDarlison** [comment]
Thanks for jumping in @alex-deaconu. @AlexKolenoff @btfrise @alanclayton how should we prioritize this? Thanks

**Comment by btfrise** [comment]
@ByronDarlison I will review this with @alanclayton this morning and get a priority established.

**Comment by alanclayton** [comment]
@alex-deaconu @ByronDarlison  Can we plan to look at this after the Displays App?

**Comment by ByronDarlison** [comment]
@alanclayton okay by me. @alex-deaconu if you concur can you queue a card up for this? Thanks!

**Comment by alex-deaconu** [comment]
@ByronDarlison yup re: priority, added https://trello.com/c/ElO4ba2V/25-viewer-doesn-t-receive-done-from-embedded-presentations-with-only-1-item. Will fix after Displays App is done. Thanks!

**Comment by btfrise** [comment]
@ByronDarlison Curious, I never saw a resolution to this bug. I have an open issue for this in the community here https://getsatisfaction.com/rise_vision_inc/topics/issue-with-embedded-presentations-play-until-done-not-detecting-presentation-length

I'd like to give an update or response as to the status of the issue.

**Comment by ByronDarlison** [comment]
@btfrise good find. I just resurrected on this card https://trello.com/c/ElO4ba2V and asked @tejohnso and @fjvallarino to review with input from @alex-deaconu. Let's resolve there. Thanks!

**Comment by tejohnso** [comment]
@btfrise Can you point me to the example presentation?  The one listed in the original description is gone.

**Comment by btfrise** [comment]
@tejohnso http://preview.risevision.com/Viewer.html?type=presentation&id=5913df00-6182-4c46-8768-7647bb08516c

**Comment by ByronDarlison** [comment]
embedded presentations are deprecated, won't fix
