### ISSUE TITLE
Fade transition only functions once when in schedule.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/viewer#68]
Steps to reproduce:
1. Create a presentation containing a placeholder with text, set the transition to fade.
2. Create a second presentation containing a placeholder with text, set the transition to fade.
3. Put both presentations into a schedule, set the duration of each presentation to a low value (3 seconds).
4. Preview the schedule.

Result:
The two text items will fade the first time through, then will not fade on further transitions.

How it should work:
The text items should fade on each transition.

Link to Presentation:
http://preview.risevision.com/Viewer.html?type=schedule&id=f22c183f-4a15-40c7-b8e9-33c86df2316d

**Comment by btfrise** [comment]
@ByronDarlison FYI

**Comment by btfrise** [comment]
RE: https://getsatisfaction.com/rise_vision_inc/topics/fade-not-working

**Comment by ByronDarlison** [comment]
@btfrise can you confirm if this is still open. Thanks

**Comment by ashleighalmeida** [comment]
@ByronDarlison This is still an issue.

The text items will fade for the first iteration, but after the schedule restarts the fade will no longer be in affect.

See: http://preview.risevision.com/Viewer.html?type=schedule&id=f7f89c8f-1443-4ad2-acb3-8ec4ef159ed2 @btfrise

**Comment by ByronDarlison** [comment]
Okay. Thanks @ashleighalmeida

**Comment by alex-deaconu** [comment]
@btfrise I cannot replicate this issue with the Schedule preview provided. Are there any particulars that I should be looking for with this? Thanks!

**Comment by btfrise** [comment]
@alex-deaconu This may have been fixed somewhere along the way. In any case, I'm seeing the images fade during each iteration now. Closing this!
