### ISSUE TITLE
Multiple embedded presentations do not appear in a complex presentation.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/viewer#71]
Steps to reproduce:
1. Create a 5760x1080 presentation
2. Add 3 1920x1080 placeholders
3. Within those placeholders, place three different 1920x1080 presentations that contain spreadsheet widgets
4. Save and preview presentation

Result:
Only the presentation in the leftmost placeholder will appear.

How it should work:
All three presentations should appear.

Link to Presentation:
http://preview.risevision.com/Viewer.html?type=presentation&id=94b41a27-9290-4d12-b8c7-70fb453e57aa (Zoom out)

Individual presentations
http://preview.risevision.com/Viewer.html?type=presentation&id=8044f1cd-95e2-4a1d-999b-b80a97f55f78
http://preview.risevision.com/Viewer.html?type=presentation&id=3d6d80e8-fe70-4bed-b237-6c56bc436a7e
http://preview.risevision.com/Viewer.html?type=presentation&id=0be8bebf-8620-4a6a-9050-80f855d8d2f4

**Comment by btfrise** [comment]
@ByronDarlison FYI.

**Comment by ByronDarlison** [comment]
embedded presentations deprecated, won't fix
