### ISSUE TITLE
embedded presentation in same placeholder with images will crash viewer on Windows OS

### ISSUE THREAD

**Issue by justinsmith1** [Rise-Vision/viewer#72]
1. Create a placeholder in a 'master' presentation, add an image (image item, image widget, or image folder widget) to that placeholder.
2. In that same placeholder, add an embedded presentation (child/embedded presentation should contain image item, image widget, or image folder widget as well).
3. Schedule master presentation to play on a Windows OS media player.

Viewer crashes with 'sad face' within 3-5 minutes.

Link to test presentation (child): http://goo.gl/kCYZCw

Link to test presentation (master): http://goo.gl/RVew9N

What should happen:
1. Viewer should display the presentations without crashing.

**Comment by justinsmith1** [comment]
@ByronDarlison I forgot to tag you on this Friday afternoon. My apologies.

**Comment by justinsmith1** [comment]
@ByronDarlison do you know where this issue falls in the backlog? I have a support ticket that called asking for an update. Thanks

**Comment by ByronDarlison** [comment]
@justinsmith1 sorry, haven't looked at this yet. To confirm, this happens with any combination of the image item, image widget or image folder widget? Is that right?

Also, does it matter what images are linked? Or is it only specific images or image combinations that cause it?

This seems like a very common setup and I am surprised that this hasn't come up before. Is there anything in particular going on here that is different that you can see? Thanks

**Comment by justinsmith1** [comment]
@ByronDarlison Correct. Any combination of image item, image widget, or image folder widget being used with an embedded presentation will crash viewer on Windows OS.

The user (U of Toronto Mississauga) have 12-13 images in the master presentation, and the roughly the same number in the embedded presentation. They are using the image item. However, in my testing, I slimmed my test presentations to have 1 image (in both the parent and child presentations) and could still replicate. I could replicate using the image item, image widget, and image folder widget. Again, I was only seeing this on Windows OS. Linux and Chrome seemed to be fine.

**Comment by ByronDarlison** [comment]
@justinsmith1 and curious, does this happen with any image, or just their image? And is this happening on latest Windows Player? Which version is it happening with? @btfrise here is a good example of what needs to included on the uptime wall. Thanks

**Comment by justinsmith1** [comment]
@ByronDarlison tested with both their images and my own.

**Comment by ByronDarlison** [comment]
@justinsmith1 what about the other questions:

What Player and Chrome Version is this happening on?

And if not the latest version, have you tried latest?

Thanks

**Comment by justinsmith1** [comment]
@ByronDarlison the NUC in question was originally running CAP on Chrome 45. Once I gained remote access, I installed the latest version of Rise Player to see if it behaved any differently. I also tested on CAP on the uptime wall on Windows 8.1 using Chrome 45 and it happened there too; on dev, beta, and stable.

Their machine is currently running:

Windows 7 Pro
RisePlayer 2015.10.12.15.11
Viewer version: 1-06-201510071813
Chrome 44.0.2403.157
Display ID: CDDG76V6MAC9

**Comment by ByronDarlison** [comment]
@justinsmith1 thanks for the clarifications. @tejohnso can you review this issue and let us know your thoughts on where the problem originates from and how you think we should go about resolving it. Thanks!

**Comment by justinsmith1** [comment]
@tejohnso did you have a chance to review this issue? Can you keep @mfisher11 in the loop here as well? He will be handling the open CS ticket going forward. Thanks! FYI @ByronDarlison

**Comment by tejohnso** [comment]
Waiting for a windows test machine to use via screenconnect

**Comment by justinsmith1** [comment]
@tejohnso You're welcome to use my Windows Test Display. Under my name in ScreenConnect (100683-DN7M). Display ID: 6AZVXF2KDN7M. It's currently running a copy of U of Toronto's content (they reported the problem initially).

**Comment by ByronDarlison** [comment]
@tejohnso @btfrise @justinsmith1 from what I can gather from the delivery room chat we can't replicate this issue on a test machine. Can you confirm where this is at? Thanks

**Comment by justinsmith1** [comment]
@ByronDarlison @tejohnso very strange. That slimmed down presentation that I created (the one Tyler is running on his test display) is no longer crashing on my test display either (it would typically do it within 5-10 minutes). U of Toronto's content, however, is still crashing within a couple of minutes (http://goo.gl/isWZD8).

**Comment by ByronDarlison** [comment]
@justinsmith1 okay. Can you set that one up on the target test display and let's watch it. @tejohnso anything in particular you need to check this out? Thanks

**Comment by justinsmith1** [comment]
@ByronDarlison @tejohnso just crashed on Win7 Stable uptime display in the same schedule that Tyler created. Display ID: FG5YVBJDTXB2

**Comment by tejohnso** [comment]
Well this is interesting.  Another difficult to reproduce problem.  I'll check it out.

**Comment by tejohnso** [comment]
@fjvallarino Is running this on his machine to see if he can replicate the issue.  So far we have one machine crashing, and one machine not crashing.

**Comment by tejohnso** [comment]
@justinsmith1 Is there anything unusual about the windows machine that's crashing?  Is it the same image as the one that is not crashing?  So far we've got two machines not crashing and one that is.

**Comment by justinsmith1** [comment]
@tejohnso Interesting. One is a NUC5i3RYK (not crashing; this is the model we started selling for Solutions a couple of months back). The other is a NUCi3-3217U (crashing; this is the model that is in the Store, and that we used to sell for about a year and a half). A majority of Windows NUCs in the wild will be the version that is crashing.

**Comment by ByronDarlison** [comment]
embedded presentations are deprecated, won't fix
