### ISSUE TITLE
Presentation audio continues to play in background when in schedule with other presentations.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/viewer#73]
Steps to reproduce:
1. Create a presentation with audio
2. Create a secondary presentation
3. Put both presentations into a schedule

Result:
The audio from presentation 1 will run, even when presentation 2 is running, creating an audio overlap if both presentations have audio.

How it should work:
Presentation 1 should not continue playing audio while presentation 2 is running.

Link to Presentation:
http://preview.risevision.com/Viewer.html?type=schedule&id=46808268-7cc5-4fc2-8de4-b1486da051ec

**Comment by btfrise** [comment]
FYI @ByronDarlison

**Comment by hcs0** [comment]
@btfrise We tested this scenario with the new Schedules change so this issue should be closed.
