### ISSUE TITLE
For more details visit [link] does not work in the Displays setup menu

### ISSUE THREAD

**Issue by lapinnoir** [Rise-Vision/viewer#76]
**How to Duplicate**
Install RV Player
Add invalid DisplayID

![linkdoesntwork](https://cloud.githubusercontent.com/assets/5868781/11915575/5d29bc28-a67a-11e5-98ab-113f4ca7f4e7.png)

**Expect outcome**
Link should go to the final Create A Display page

**Environment**
Found during Win 10 32bit testing but applicable with other OS

**Comment by ByronDarlison** [comment]
@lapinnoir where does the help button go to? Thanks!

**Comment by lapinnoir** [comment]
@ByronDarlison When you click on the Help button a new window frame appears but you can't tell what the link is since there is no URL browser.  I think it leads to http://help.risevision.com/#/user/player/register-player (referenced in https://github.com/Rise-Vision/viewer/blob/99a87b86e6222ff744104c3e21dac979be71a2f8/src/main/java/com/risevision/viewer/client/widgets/oem/HelpFrameWidget.java ) cc @fjvallarino

**Comment by ByronDarlison** [comment]
@lapinnoir okay. Can we remove the first help reference in the text and just update the Help button to point to https://help.risevision.com/user/create-a-display. Thanks!

**Comment by lapinnoir** [comment]
Merged
https://github.com/Rise-Vision/viewer/pull/78
https://github.com/Rise-Vision/viewer/pull/77
