### ISSUE TITLE
Content can be swiped off screen.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/viewer#80]
How to recreate:
1. Create a presentation with any piece of content
2. Add this presentation to a schedule
3. Schedule this presentation to an interactive display

What happens:
When interacting with the presentation, if you hold your finger on top of a content widget, and swipe either direction, the content may swipe off the screen, restarting the presentation, or making the piece of content disappear.

What should happen:
When interacting with presentations, all content should maintain it's set position, and swiping should not cause a refresh of stoppage of the presentations.

Example presentation:
http://preview.risevision.com/?type=presentation&id=cec673e7-9151-4f94-bf82-4f6f202f2d14&showui=false

Example schedule:
http://bit.ly/1KbcBVY

Example video:
https://www.dropbox.com/s/mubq0rs8q8d435i/VID_20151231_161429.mp4?dl=0

Video followup, I have been able to recreate this with a widget placeholder set to full screen (1920x1080).

**Comment by ByronDarlison** [comment]
Not sure what to make of this so I going to circle everyone in so that we can figure out who owns this. @tejohnso @fjvallarino @alanclayton @rodrigopavezi @ezequielc @alex-deaconu what do you guys think? Where should we start? FYI @robb-price 

Thanks!

**Comment by tejohnso** [comment]
@robb-price Are we getting many user complaints on this?  Otherwise @ByronDarlison I don't think this should be a high priority issue.

**Comment by ByronDarlison** [comment]
@tejohnso why don't you think it should be high priority?

**Comment by robb-price** [comment]
@tejohnso @ByronDarlison  No, we haven't had any complaints about it yet, which is honestly very surprising with how easy it is to recreate.

**Comment by tejohnso** [comment]
@ByronDarlison Because we don't have any users mentioning it, as opposed to some other issues.  I think those should take priority.   Also this is something that only happens due to a specific user action so it's not going to affect many displays.

**Comment by ByronDarlison** [comment]
@tejohnso my worry is this is something newly introduced and it could become a big problem quickly. @btfrise @robb-price curious, can you replicate this with older Chrome versions?

**Comment by robb-price** [comment]
@ByronDarlison @btfrise will test shortly and let us know. I was able to replicate it with an older Chrome version (v 46), but I want to make sure it was not unique to my environment.

**Comment by ByronDarlison** [comment]
Thanks @robb-price

**Comment by btfrise** [comment]
@robb-price I was able to replicate this with the old installer using Chrome 46 as well.

FYI @ByronDarlison

**Comment by ByronDarlison** [comment]
@btfrise thanks! @tejohnso do you think Ahmed could take investigating this and also investigating whether or not it happens with Electron? Thanks

**Comment by ahmedalsudani** [comment]
@ByronDarlison just tested Electron. Doesn't seem to be an issue under Electron.

**Comment by ByronDarlison** [comment]
@ahmedalsudani good to know. And to confirm, can we fix this for the current chrome version as well? Thanks

**Comment by ahmedalsudani** [comment]
@ByronDarlison found an easy fix for Chrome. Trying to get it to work. So it should be a yes

**Comment by ByronDarlison** [comment]
AWESOME. Thanks

**Comment by hcs0** [comment]
https://trello.com/c/Cl65yzPO/1337-2-test-swipe-solution-on-win10-and-win7

**Comment by btfrise** [comment]
Confirmed as fixed.
