### ISSUE TITLE
Scott's Vimeo Widget won't play Videos/Channel IDs with numbers in the channel.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/viewer#85]
How to recreate the issue:
1. Create a presentation with the Vimeo Widget in a placeholder
2. Select a Video or Channel ID with numbers, ex. 11075198
3. Preview the presentation, or assign to a display.

What happens:
The video does not appear.

What should happen:
The video should appear.

Presentation:
https://apps.risevision.com/editor/workspace/26ffc0fe-1b20-483e-be37-b618bb653000/?cid=f114ad26-949d-44b4-87e9-8528afc76ce4

Further history:
@rodrigopavezi fixed a similar issue on the 18th of December, the commit is here. https://github.com/Rise-Vision/viewer/commit/4d040d76c1b148c3b161296ec3fe21db44b2ab0f
Object {text: "1001803 not found.", rc: 500, errors: Array[2], data: null}
data: null
errors: Array[2]
rc: 500
text: "1001803 not found."
No videos found in channel

**Comment by woneal1983** [comment]
This can be closed its fixed .

**Comment by btfrise** [comment]
Verified fixed.
