### ISSUE TITLE
Vimeo Channel issue

### ISSUE THREAD

**Issue by woneal1983** [Rise-Vision/viewer#88]
Blake and i have been discussing this almost everytime there is an update to the viewer. 

The issue is with vimeo not getting channels when the vimeo widget is using a numbered channel. 

For your test, the settings in the widget need to be a valid channel id like 12949172 with channel playback option being one of the channel ids. You will notice that in the debugging it will come out as no channels available. If you use staffpicks as a channel id though it will work. When we use this in the app previewer to test this widget it works as its supposed to. It only has issues when in viewer.

**Comment by ezequielc** [comment]
@woneal1983 Can you confirm the Vimeo API URL you are using? If it is https://vimeo.com/api/v3/channel/staffpicks/videos.json, it is returning "Page not found" from Vimeo.

Thanks

**Comment by ezequielc** [comment]
@woneal1983 Any chances of being v2 instead of v3 in api call? Thanks!

**Comment by woneal1983** [comment]
I was playing with it to see if there was any difference between v2 and v3. It should be v2. I was doing some testing when you tried. Sorry about that it should be back as v2.

**Comment by ezequielc** [comment]
@woneal1983 Now that you changed to v2, I tried with Channel ID 1341 and it works fine.
The Channel ID 12949172 doesn't exist in Vimeo and the return from API is "Not Found".

@btfrise Another thing I realized is that if you use 'user3254350' it will not work because it is not a channel, it is a user id. 

Are you guys good with closing this issue?

Cheers

**Comment by woneal1983** [comment]
I actually think i have it working now. I was messing around with it and decided to do a small change in the call. I think there is an issue on vimeos side of things as well. I might change the json call to a jsonp. From my end that looks like a better choice because it seems to work on my end better. I will update the widget to reflect the change but you can close the call now that i have it working on an updated app.

**Comment by ezequielc** [comment]
That is great. Thanks @woneal1983 . Cheers!
