### ISSUE TITLE
Empty placeholder with background color does not respect scheduling.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/viewer#92]
How to replicate
1. Create a new presentation
2. Create a placeholder
3. Do not assign any content to that placeholder, assign a black background to it, schedule it to display only during a certain time (Ex. 01:00PM - 01:45PM).
4. Assign this presentation to a schedule, and that schedule to a display.

What happens
After 01:45PM, the placeholder is still visible.

What should happen
The empty placeholder should respect scheduling.

Notes
Demo presentation here

This was test in both Editor and Classic editor, with the same result.

**Comment by robb-price** [comment]
Verified and Closed
