### ISSUE TITLE
Timeline setting not followed by the Text Widget if it span across two days

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/viewer#97]
**How to recreate the issue**
1. Add the text Text Widget with the following timeline settings within the Widget:
Time: **8pm** Thurs 26 May to **5.30am** Fri 27 May
Weekly on Thurs and Friday

<img width="567" alt="screen shot 2016-05-26 at 12 47 28 pm" src="https://cloud.githubusercontent.com/assets/5868781/15582682/3d1e5f36-2340-11e6-9b50-e00a4bb7276c.png">

2. Set Display timezone to be 7pm Thurs 26 May.  

3. Publish to a Display

**What should happen**
The Text Widget shows whereas it should start at 8pm Thurs 26 May.
![textwidgettiming1](https://cloud.githubusercontent.com/assets/5868781/15582804/d7a56b26-2340-11e6-999d-8614bc838dce.png)

If you change the Display timezone, the Text Widget also shows as indicated in the timeline.
![textwidgettiming2](https://cloud.githubusercontent.com/assets/5868781/15582849/02d3f02e-2341-11e6-84a6-106f9c03707f.png)

**Notes**
The user also had a Video Widget. It has the same settings as the Text Widget but it's following the timeline.  I have not looked into other core content to see if the issue appears elsewhere.
<img width="568" alt="screen shot 2016-05-26 at 12 51 16 pm" src="https://cloud.githubusercontent.com/assets/5868781/15582766/a651f63e-2340-11e6-88bf-c26e932d75c1.png">

You can copy this presentation https://apps.risevision.com/editor/workspace/a65534b9-03cf-4beb-9bd1-f091e3118619/?cid=960b72df-9af7-476b-8a47-b67ded4c779d where I've added the Date/Time Widget to confirm the date/time.

**Comment by hcs0** [comment]
https://app.intercom.io/a/apps/d85f4ah4/inbox/conversation/4873053391

**Comment by tejohnso** [comment]
@alanclayton Any input on this one?

**Comment by alanclayton** [comment]
@tejohnso Widget doesn't have any control over when it shows or not.  At least I don't think it does. Sounds like something with Viewer.

@donnapep @stulees Thoughts?

**Comment by stulees** [comment]
@alanclayton @tejohnso The Widget only communicates with Viewer to send the "ready" command and "done" command. For Text Widget, "done" is sent when the content is completed auto scrolling to the end of the content. However if the widget is not configured to auto scroll or there's not enough content to scroll, "done" is never fired since there's nothing to measure it being done. 

The presentation that @hcs0 has provided does not configure the Widget to auto scroll, hence "done" will never be fired. So showing/hiding the Widget is solely up to Viewer in this scenario. I do notice that Play Until Done is checked in the playlist item settings of Text Widget. Perhaps this in combination with timeline settings is causing an issue?

**Comment by alanclayton** [comment]
@hcs0 can you remove the play until done option and confirm if you still have the problem?

**Comment by hcs0** [comment]
@alanclayton @stulees Thanks -  deselecting Play Until Done in the Text Widget has resolved the issue.  I've made a couple of tests changing the timezone on my test Display.  Is this a user issue where PUD needs to be deselcted or still a Widget/viewer bug?

**Comment by alanclayton** [comment]
@hcs0 this is a design issue where PUD shouldn't be selectable if the widget doesn't support it. This will be addressed at a later date. For now, can you explain the situation to the user and have them remove PUD?

**Comment by hcs0** [comment]
@alanclayton Yes, I've contacted the user about deselecting PUD.  Do I leave this issue open or re-open back into the Widget repo?

**Comment by ByronDarlison** [comment]
@alanclayton @hcs0 can you confirm this issue should be closed or, if it is still open, I don't think it should be here, it should be in the text widget repo. Please confirm. Thanks

**Comment by alanclayton** [comment]
@ByronDarlison we can close it. Thanks
